### ISSUE TITLE
update docs for --no-prefix to specify limitations

### ISSUE THREAD

**Issue by joejansen** [Betterment/testtrack-cli#37]
instead of `Don't prefix experiment with app_name (supports legacy splits)` should we say something more verbose like `Don't prefix experiment with app_name. Do not use for any new splits, this flag is only meant for modifying existing legacy splits`?

**Comment by rnackman** [comment]
Could we remove `--no-prefix` as a flag from the docs for the `create experiment` command entirely and show it only for other commands where it applies? Or am I not following?

**Comment by jmileham** [comment]
It actually exists here so you can revive an unprefixed retired experiment/feature gate in an emergency, which will work as expected, we just really want to keep people from creating brand new unprefixed splits. We should def think about the most locked down way we can get the behavior we need to operate safely though.
